#Project Setup
general:
  githubApiUrl: 'https://api.github.com'
  githubServerUrl: 'https://github.com'
  gitSshKeyCredentialsId: 'ssh-key-os'
  githubTokenCredentialsId: 'github-token-os'

steps:
  updatePackageRefs:
    deps: ["github.com/georgi-bozhinov/service-broker-proxy"]
    skipDepRebuild: true
  pushChangesToRepo:
    branch: 'new-version'
  pollBuilds:
    timeoutSeconds: 30
    pollIntervalSeconds: 5
    branch: 'new-version'
  buildDepProjects:
    projects: ["release-k8s-broker-proxy-sap"]
  XMakeBuild:
    buildWithXMake: false

  setupPipelineEnvironment:
    buildDiscarder:
      daysToKeep: -1
      numToKeep: 10
      artifactDaysToKeep: -1
      artifactNumToKeep: -1
    configYmlFile: '.pipeline/config.yml'
    githubApiUrl: 'https://api.github.com'
    gitHttpsUrl: 'https://github.com/${githubOrg}/${githubRepo}.git'
    gitSshUrl: 'git@github.com:${githubOrg}/${githubRepo}.git'
    relatedLibraries:
    - 'piper-lib-os'
    - 'piper-lib'
    storeGithubStatistics: false
